services:
  flask:
    build: ./flask
    container_name: flask
    ports:
      - "5000:5000"
    environment:
      POSTGRES_HOST: POSTGRES_HOST
      POSTGRES_DB: POSTGRES_DB
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
    depends_on:
      - db
  db:
    image : postgres:15
    restart : always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db:/var/lib/postgresql/data
      